name: deploy-html

on:
  push:
    branches: [ master ]

env:
  AWS_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/S3-role-2
  AWS_REGION: ${{ secrets.AWS_REGION }}
  DISTRIBUTION: ${{ secrets.DISTRIBUTION }}

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [18]

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      # with:
      #     fetch-depth: 1

    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}

    # - name: build
    #   working-directory: ./client
    #   run:
    #     npm install
    #     npm run build

  #   - name: Upload build result
  #     uses: actions/upload-artifact@v1
  #     with:
  #       name: build
  #       path: client/dist/

  # deploy:
  #   needs: build

  #   runs-on: ubuntu-latest


    # - name: Download build result
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: build
    #     path: client/dist/

    # defaults:
    # run:
    #   working-directory: wrp


    - name: Configure AWS credentials from IAM Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}
        role-session-name: GitHubActionsSession

    - name: Publish to AWS S3
      uses: opspresso/action-s3-sync@master
      # with: 
      #   working-directory: wrp
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
        FROM_PATH: "."
        DEST_PATH: "s3://petmatching-lp.lobiter.site"



    # - name:  Copy documents to s3
    #   # working-directory: wrp
    #   run: |
    #     aws s3 cp --recursive -region ${{ env.AWS_REGION }} wrp s3://petmatching-lp.lobiter.site
    #   # run:
    #   #   aws s3 sync --delete --region ap-northeast-1 ./wrp/ s3://petmatching-lp.lobiter.site

     

    - name: Clear cache in CloudFront
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        DISTRIBUTION: ${{ env.DISTRIBUTION }}
        PATHS: "/*"
        AWS_REGION: ${{ env.AWS_REGION }}
