name: PetLp
on:
  push:
      branches:
        - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # リポジトリをチェックアウト


      - name: Deploy  # S3にデプロイです
        env:
            AWS_ACCESS_KEY_ID: AKIAXQR7QTG4RXLWUREB
            AWS_SECRET_ACCESS_KEY: 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
        run: |
        aws s3 cp --recursive --region ap-northeast-1 ./pet_LP/ s3://petmatching-lp.lobiter.site